version: 2.1

jobs:
  lint-code:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            echo "Setup Python virtual environment..."
            make setup
            echo "Install dependencies..."
            make install
            echo "Install hadolint..."
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && \
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./devenv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Linting code
          command: |
            make activate
            make lint

  build-docker-image:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - setup_remote_docker:
          version: 20.10.17
      - run:
          name: Build Docker image
          command: |
            docker build -t simple-hello-world-app:latest .
            docker images


workflows:
  default:
    jobs:
      - lint-code
      - build-docker-image:
          requires:
            - lint-code
          filters:
            branches:
              only: [main]
          

