version: 2.1

jobs:
  lint-code:
    docker:
      - image: python:3.7.9
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            echo "Setup Python virtual environment..."
            python -m venv venv
            cd venv
            ls -a
            cd bin
            ls -a
            source venv/bin/activate
            echo "Install dependencies..."
            make install
            echo "Install hadolint..."
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && \
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Linting code
          command: |
            source venv/bin/activate
            make lint

workflows:
  default:
    jobs:
      - lint-code
          

