version: 2.1

jobs:
  lint-code:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            echo "Setup Python virtual environment..."
            make setup
            echo "Install dependencies..."
            make install
            echo "Install hadolint..."
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && \
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./devenv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: Linting code
          command: |
            make activate
            make lint

  build-and-push-docker-image:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.17
      - run:
          name: Build Docker image
          command: |
            make activate
            docker build -t simple-hello-world-app:latest .
            docker images
      - run:
          name: Push image to Docker Hub
          command: |
            echo "Login to Docker Hub..."
            docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"
            echo "Tag image..."
            docker tag simple-hello-world-app simple-hello-world-app:${CIRCLE_WORKFLOW_ID:0:7}
            echo "Push image to Docker Hub..."
            docker push "$DOCKER_HUB_USERNAME"/simple-hello-world-app:${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      - lint-code
      - build-and-push-docker-image:
          requires:
            - lint-code
          filters:
            branches:
              only: [main]